services:
  - type: web
    name: plc-qa-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT production_dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: plc-qa-dashboard
          property: host
